### ISSUE TITLE
Add Contribution Guidelines

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/Python-Scripts-and-Games#8]

**Comment by aashutoshrathi** [comment]
The label prediction failed because there are not enough labels. Three labels must have been set on at least three issues each.

The contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by Raman1121** [comment]
Hey! Can you explain a bit more as to what has to be done? @aashutoshrathi

**Comment by alexandrebarbaruiva** [comment]
Isn't it the owner's task?

**Comment by jangidkrishna** [comment]
I gave it a try please give it a look

**Comment by jangidkrishna** [comment]
#10
